# model
mt5:
  model_checkpoint: google/mt5-small
  max_input_length: 784
  max_output_length: 128

#data
data_dir: /dir
train_size: 0.8
valid_size: 0.1

# training
output_dir: dir

learning_rate: 0.1
weight_decay: 0.01
save_total_limit: 3
num_train_epochs: 1
save_checkpoint_steps: 5000
valid_steps: 5000
batch_size: 16
warmup_steps: 3000

