# model
mt5:
  model_checkpoint: google/mt5-small
  max_input_length: 784
  max_output_length: 128

#data
data_dir: /dir
train_size: 0.8
valid_size: 0.1

# training
output_dir: dir

learning_rate: 10e-4
weight_decay: 0.01
save_total_limit: 3
num_train_epochs: 10
batch_size: 16
save_steps: 1000




