# model
mt5:
  vmi: 10
  model_checkpoint: mt5-small
bert2bert:
  vmi: 10

#data
data_dir: /dir
train_size: 0.8
valid_size: 0.1

# training
learning_rate: 1
weight_decay: 0.01
save_total_limit: 3
num_train_epochs: 1
batch_size: 16

